[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
gold_pegged_token = "BddZyxYaMEnRSBMjqjYMLbGzwfnZwXggB8FFoLYC5hED"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
